<?php
/**
 * Customer Product list.
 *
 * @category  Ecommistry
 * @package   Ecommistry_ProductList
 * @author    Sumil
 * 
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Ecommistry\ProductList\Block\Index\Index
 */
?>
<?php

if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
	$currentmode = $block->getCurrentMode();
	$type = 'widget-viewed';
	if($currentmode == 'slider'){
		$mode = 'grid';
	}else{
		$mode = 'list';
	}
	$type = $type . '-' . $mode;

	$image = 'recently_viewed_products_grid_content_widget';
	$items = $block->getProductCollection();

	$showWishlist = true;
	$showCompare = true;
	$showCart = true;
	$rating = 'short';
	$description = ($mode == 'list') ? true : false;

}
?>

<?php if ($exist):?>
	<div class="content-top">
	<?php if($currentmode == 'list' || $currentmode == ''){ ?>
				<a href="<?php echo $this->getUrl('productlist/index/index'); ?>?mode=slider">Slider Mode</a>
	<?php  }else{ ?>
				<a href="<?php echo $this->getUrl('productlist/index/index'); ?>?mode=list">List Mode</a>
	<?php  } ?>
	</div>
	    <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
			<div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php $iterator = 1; ?>
					<div class="<?php echo ($currentmode == 'slider') ? 'owl-carousel' : ''; ?>" id="custom-product-slider">
					<?php foreach ($items as $_item): ?>
						<?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item product-slider">' : '</li><li class="product-item product-slider">' ?>
						<div class="product-item-info">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="mp-product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
									   href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
								<?php /* @escapeNotVerified */ echo $block->getProductPriceHtml(
									$_item,
									\Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
									\Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
									[
										'price_id_suffix' => '-' . $type
									]
								) ?>
								<?php if ($rating): ?>
									<?php echo $block->getReviewsSummaryHtml($_item, $rating) ?>
								<?php endif; ?>
								<?php if ($showWishlist || $showCompare || $showCart): ?>
									<div class="product-item-actions">
                                        <?php if ($showCart): ?>
											<div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
													<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
														<button class="action tocart primary"
																data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
																type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
													<?php else: ?>
														<?php
														$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
														$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
														?>
														<button class="action tocart primary"
																data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
																type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
													<?php endif; ?>
												<?php else: ?>
													<?php if ($_item->getIsSalable()): ?>
														<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
                                            </div>
										<?php endif; ?>
										<?php if ($showWishlist || $showCompare): ?>
											<div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
													<a href="#"
													   class="action towishlist" data-action="add-to-wishlist"
													   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
													   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                    </a>
												<?php endif; ?>
												<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
													<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
													<a href="#" class="action tocompare"
													   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
													   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                    </a>
												<?php endif; ?>
                                            </div>
										<?php endif; ?>
                                    </div>
								<?php endif; ?>
                            </div>
                        </div>
						<?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
					<?php endforeach ?>
					</div>
                </ol>
            </div>

        </div>
        <?php if($currentmode =='slider'){ ?>
	<script>
			require([
				'jquery',
				'Ecommistry/ProductList/js/owl.carousel.min'
			], function ($) {
				$('#custom-product-slider').owlCarousel({
					loop:true,
					nav:true,
				});
			});
	</script>
	<?php  } ?>
<?php else: ?>
	<div class="message empty">No product found</div>
<?php endif;?>


